---
title: "Assignment 3"
author: "Vikash Kumar Pandey(MT18086)"
date: "OCT 27, 2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
    
subtitle : Question 1 - 
 i) In the figure, goog200 is going upwards as per the day(unit time) is increasing so this will result variability in mean across the time series (not constant mean) thats why data is NOT stationary.
 iii) The time series which is given have variablity in mean during two time intervals 1950-1965 and  1970-1980 therefore the data is not stationary.
  v) Because the timeseries is getting decreased over time, so the mean is not constant because of variability in mean over the time make data non stationary. 
  ix)  Because the timeseries is getting increased over time, so the mean is not constant because of variability in mean over the time make data non stationary.
  
  Rest of them (ii), iv),vi), vii), viii) are stationary. 


subtitle : Question 3 
---

```{r, echo=FALSE, message=FALSE, fig.align="center"}
library(magrittr)
library(caret) 
library(ROCR)
library(ggplot2)
library("RColorBrewer")
library("gplots")
library(readr) 
library(dplyr) 
library(tidyr) 
library(gridExtra)
library(grid)
library(plyr)
library(GGally)
library(caTools)

library (mlbench)
```
READ DATA

```{r, echo=FALSE, message=FALSE, fig.align="center"}
data("BreastCancer")
summary(BreastCancer)
library (mice)
```


```{r, echo=FALSE, message=FALSE, fig.align="center"}
newD = BreastCancer[,c(1:10)]
set.seed(1)
breast_cancer = complete(mice(newD, printFlag = FALSE))
breast_cancer <- cbind(BreastCancer, class = BreastCancer$Class)
summary(breast_cancer)

```

Deleting S.No and Id from dataset because not such relevent features.

```{r, echo=FALSE, message=FALSE, fig.align="center"}
breast_cancer$S.No <- NULL
breast_cancer$Id <- NULL
```


```{r, echo=FALSE, message=FALSE, fig.align="center"}
summary(breast_cancer)
```



```{r, echo=FALSE, message=FALSE, fig.align="center"}

newD = breast_cancer[,c(1:9)]
set.seed(1)
newData = complete(mice(newD, printFlag = FALSE))
newData <- cbind(newData, class = breast_cancer$Class)
summary(newData)

set.seed(1)
split = sample.split(newData$class, SplitRatio = 0.70)
train = subset(newData, split==TRUE)
test = subset(newData, split==FALSE)

```


```{r, echo=FALSE, message=FALSE, fig.align="center"}
# set.seed(1)
# breast_cancerPP <- preProcess(x = breast_cancer, method = c("center", "scale")) 
# breastcancerdatapp <- predict(breast_cancerPP, breast_cancer)
# traindataindex <- createDataPartition(breastcancerdatapp$Class, times = 1,p = .75, list = FALSE)
# traindata <- breastcancerdatapp[traindataindex,]
# testdata <- breastcancerdatapp[-traindataindex,]
# # testValues <- testdata$Class
# fit <- glm(F~x1+x2+x3,data=mydata,family=binomial())
# summary(fit)
# confint(fit) # 95% CI for the coefficients
# exp(coef(fit)) # exponentiated coefficients
# exp(confint(fit)) # 95% CI for exponentiated coefficients
# predict(fit, type="response") # predicted values
# residuals(fit, type="deviance") # residuals
```

Fit data by GLM
```{r, echo=FALSE, message=FALSE, fig.align="center"}
set.seed(1)
modelfit <- glm(class ~., family = binomial(link = "logit"), data = train)
summary(modelfit)

```


```{r, echo=FALSE, message=FALSE, fig.align="center"}
rfPredict <- predict(glmCancerFit,newdata = test)
confusionMatrix(rfPredict, test$class)
```

